### ISSUE TITLE
xml2json: Translate CSDL references for all repositories

### ISSUE THREAD

**Issue by HeikoTheissen** [oasis-tcs/odata-csdl-schemas#29]
https://github.com/oasis-tcs/odata-csdl-schemas/blob/dc162926eca3dc03e7688d991532a01f676bb661/lib/xml2json.js#L198-L199

The same should apply to vocabularies in other repositories.

**Comment by ralfhandl** [comment]
Please review https://github.com/oasis-tcs/odata-csdl-schemas/pull/30
