### ISSUE TITLE
ontext handler assumes text coming in one chunk

### ISSUE THREAD

**Issue by HeikoTheissen** [oasis-tcs/odata-csdl-schemas#43]
https://github.com/oasis-tcs/odata-csdl-schemas/blob/c3d668f6910801fb7e5f2e6c1c17e2d25f15a824/lib/xml2json.js#L722-L724

Can we be sure that all text comes in *one* event? According to the [SAX specification](http://www.saxproject.org/apidoc/org/xml/sax/ContentHandler.html#characters(char[],%20int,%20int)#:~:text=SAX%20parsers%20may,chunks), text may be delivered in several chunks.

**Comment by ralfhandl** [comment]
I assume yes because the documentation of `sax-js` does not talk about chunks in `ontext`: https://github.com/isaacs/sax-js#usage

**Comment by HeikoTheissen** [comment]
https://github.com/isaacs/sax-js/blob/5aee2163d55cff24b817bbf550bac44841f9df45/lib/sax.js#L632-L636

looks indeed as if `sax-js` collects all text before emitting `ontext`.
