### ISSUE TITLE
csdl.schema.json incorrect default for $HasStream

### ISSUE THREAD

**Issue by hylkevds** [oasis-tcs/odata-csdl-schemas#48]
https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/odata-csdl-json-v4.01.html#_Toc38466411
> The value of $HasStream is one of the Boolean literals true or false. Absence of the member means false.

https://docs.oasis-open.org/odata/odata-csdl-json/v4.01/os/schemas/csdl.schema.json
```
        "$HasStream": {
          "description": "Media entity type",
          "type": "boolean",
          "default": true
        },
```

I suppose the schema should have `"default": false` ?

(I hope this is the right place to report this.)

**Comment by ralfhandl** [comment]
Hi @hylkevds,

Thanks for reporting this, and this is the right place to report this.

As explained in [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/reference/generic.html#id2)

> The default keyword specifies a default value. This value is not used to fill in missing values during the validation process. Non-validation tools such as documentation generators or form generators may use this value to give hints to users about how to use a value.

We use the `default` keyword for the value that code completion should fill in. This works nicely for example in VS Code. Of course the most useful value that you want to explicitly type for a Boolean property is the opposite of the value that is assumed if the property is not present.

Hope this explains our use of JSON Schema's `default`.

**Comment by hylkevds** [comment]
That's a bit confusing, especially since right after the bit you quoted comes:

> However, default is typically used to express that if a value is missing, then the value is semantically the same as if the value was present with the default value.

Which is apparently not the case here... Is this documented somewhere?
