### ISSUE TITLE
sap:sortable="false" sap:filterable="false" sap:pageable="false" aren' honored?

### ISSUE THREAD

**Issue by sterlp** [oasis-tcs/odata-csdl-schemas#76]
Could it be, that the SAP sap:sortable="false" sap:filterable="false" sap:pageable="false" aren' honored, or is the XML wrong?

![image](https://user-images.githubusercontent.com/774984/220915224-4bed2554-870e-4051-81af-f4e71f5a0074.png)

https://github.com/oasis-tcs/odata-openapi/pull/230

**Comment by ralfhandl** [comment]
@sterlp Hi Paul, could you please check whether this fixes your issue?

**Comment by sterlp** [comment]
Thanks! I will try it out tomorrow or the day after.

**Comment by ralfhandl** [comment]
@sterlp You can check https://github.com/oasis-tcs/odata-openapi/pull/234/files whether these are the expected differences: no $top, $skip, $orderby any more, and version:1

**Comment by sterlp** [comment]
Hello @ralfhandl,

looks much better, version etc. is working now. The following stuff is still added:


```json
                ],
                "parameters": [
                    {
                        "name": "$filter",
                        "description": "Filter items by property values, see [URI Conventions (OData Version 2.0)](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)",
                        "in": "query",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "$ref": "#/components/parameters/count"
                    },
                    {
                        "name": "$select",
                        "description": "Select properties to be returned, see [URI Conventions (OData Version 2.0)](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/)",
                        "in": "query",
                        "explode": false,
                        "schema": {
                            "type": "array",
                            "uniqueItems": true,
                            "items": {
                                "type": "string",
                                "enum": [
                                    "DummyKey",
                                    "Client"
                                ]
                            }
                        }
                    }
                ],
                "responses": {
```

I think **count** is part of the paging, right? Means it should be gone? Furthermore we have one more field **filterable** which isn't considered:

![image](https://user-images.githubusercontent.com/774984/222101633-7a5a5344-78fa-459c-8850-d923f8fa3287.png)

**Comment by ralfhandl** [comment]
> 1. I think **count** is part of the paging, right? Means it should be gone with **sap:pageable="false"**?

No, count can and needs to be turned off separately via `sap:countable="false"`. This is now translated into V4 annotations:
https://github.com/oasis-tcs/odata-csdl-schemas/blob/111d6725d8100f9553d763e08b24d7d7f5649266/lib/xml2json.js#L1885-L1890

**Comment by ralfhandl** [comment]
> 2\. Furthermore we have one more field **filterable** which isn't considered.

`sap:filterable` is considered when translating CSDL XML to CSDL JSON:
https://github.com/oasis-tcs/odata-csdl-schemas/blob/111d6725d8100f9553d763e08b24d7d7f5649266/test/v2-annotations.xml#L33-L36
results in
https://github.com/oasis-tcs/odata-csdl-schemas/blob/111d6725d8100f9553d763e08b24d7d7f5649266/test/v2-annotations.json#L85-L90

The `NonFilterableProperties` just don't have a visible effect on the OpenAPI output.
